Parameters:
  GitHubToken:
    Type: String
    Description: >-
      GitHub personal token, needs to have repo and admin:repo_hook
  
  SecretToken:
    Type: String
    Description: >-
      Token to authenticate webhook invoked by GitHub
    Default: 49884ae0b2b0dfc8cdd5c8f87c2cd71ffa130e49

Resources:
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
  
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactStoreBucket
        Type: S3
      DisableInboundStageTransitions: []
      RoleArn: arn:aws:iam::460449571267:role/service-role/AWSCodePipelineServiceRole-us-east-1-codepipeline
      Stages:
      - Name: Source  
        Actions:
        - Name: Source
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: '1'
            Provider: GitHub
          OutputArtifacts:
          - Name: GHSource
          Configuration:
            Owner: novantis
            Repo: cfn-simple
            PollForSourceChanges: false
            Branch: master
            OAuthToken: !Ref GitHubToken 
      - Name: Deploy
        Actions:
        - Name: Deploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
          - Name: GHSource
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: arn:aws:iam::460449571267:role/codepipeline
            StackName: case
            TemplatePath: "GHSource::repro.yaml"
          RunOrder: 1
  
  Webhook:
    Type: AWS::CodePipeline::Webhook
    DependsOn:
    - ArtifactStoreBucket
    - Pipeline
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref SecretToken 
      Filters:
      - JsonPath: '$.ref'
        MatchEquals: 'refs/tags/v1.0.0'
      TargetAction: Source
      TargetPipeline: !Ref Pipeline
      TargetPipelineVersion: !GetAtt Pipeline.Version
      RegisterWithThirdParty: true