AWSTemplateFormatVersion: '2010-09-09'
Description: Repro for case 5508726811

Resources:
  Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub '${AWS::StackName}-afro-named-policy'
      Roles:
      - !Ref Role
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:DescribeLogStreams"
          - "logs:PutLogEvents"
          - "logs:GetLogEvents"
          Resource: '*'

  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${AWS::StackName}-repro-role'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - "ec2.amazonaws.com"
          Action:
          - "sts:AssumeRole"